### ISSUE TITLE
second half of task list

### ISSUE THREAD

**Issue by Archeleus21** [Archeleus21/Test-Project#2]
9) [ ] [Extra credit] Automate your build process so that it happens weekly
10) [x] Setup a Discord channel for your project and invite everyone else in the class
11) [ ] Add a "tool" using C# to Unity Editor (the tool can be purely visual and non-functional -- it should be related to your project)
12) [x] Write a definition of "unit tests" and email it to me
13) [x] Create a single unit test for your project
14) [x] Learn the definition of man-month and estimate the man month production cost of taking your project to a "full and complete prototype"
15) [x] Identify an area of computer engineering you feel you need more understanding of and tell me.
16) [x] Put all of these tasks in Github in your project and assign them to yourself.
17) [ ] Add me to your Github project and give be the necessary permissions to view everything
18) [x] [Optional] Add the other students to your Github project
